from pydantic import BaseModel, StrictInt, StrictStr


class Result(BaseModel):
    statusCode: StrictInt = ...
    result: StrictInt = ...


class State(BaseModel):
    statusCode: StrictInt = ...
    state: StrictStr = ...


class Status(BaseModel):
    statusCode: StrictInt = ...
    statusMessage: StrictStr = ...
